title: Youni's Blog
description: 기록하고 정리하는 GitHub Pages 블로그
theme: just-the-docs

url: "https://youni202.github.io"
baseurl: "/blog0425"

permalink: pretty
lang: ko-KR
search_enabled: true
heading_anchors: true
color_scheme: light

aux_links:
  "GitHub 저장소":
    - "https://github.com/youni202/blog0425"

gh_edit_link: true
gh_edit_link_text: "GitHub에서 이 페이지 수정하기"
gh_edit_repository: "https://github.com/youni202/blog0425"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

callouts:
  note:
    title: 메모
    color: blue
  highlight:
    title: 강조
    color: yellow
  tip:
    title: 팁
    color: green
